name: Android CI (Java 8 Legacy)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. 使用 Java 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      # 2. 安装兼容 Java 8 的 Android SDK（使用 2019 年版本）
      - name: Install Legacy Android SDK
        run: |
          # 创建必要的目录结构
          mkdir -p $ANDROID_HOME/{licenses,platforms,build-tools}
          
          # 接受所有许可证
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
          
          # 下载真正兼容 Java 8 的 SDK 工具（2019 年版本）
          wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          unzip -q sdk-tools-linux-*.zip -d $ANDROID_HOME
          rm sdk-tools-linux-*.zip
          
          # 设置环境变量
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          
          # 安装必要组件（使用旧版 SDK 管理器）
          yes | $ANDROID_HOME/tools/bin/sdkmanager --install \
            "platforms;android-28" \
            "build-tools;28.0.3" \
            "platform-tools" \
            "tools"

      # 3. 配置 Gradle 使用 4.10.3（完全兼容 Java 8）
      - name: Configure Gradle Wrapper
        run: |
          # 使用 Gradle 4.10.3
          sed -i 's/distributionUrl=.*/distributionUrl=https\\:\/\/services.gradle.org\/distributions\/gradle-4.10.3-bin.zip/' gradle/wrapper/gradle-wrapper.properties
          
          # 确保 gradlew 使用正确的 Gradle 版本
          ./gradlew --version || true

      # 4. 验证环境
      - name: Verify Environment
        run: |
          java -version
          $ANDROID_HOME/tools/bin/sdkmanager --list
          ./gradlew --version

      # 5. 构建项目
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
