name: Android CI (Java 8 Legacy)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. 设置 Java 8 环境
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      # 2. 安装兼容的 Android SDK
      - name: Install Legacy Android SDK
        run: |
          # 创建基础目录
          ANDROID_HOME=/usr/local/android-sdk
          sudo mkdir -p $ANDROID_HOME
          sudo chmod -R 777 $ANDROID_HOME
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          
          # 设置权限
          sudo chmod -R 777 $ANDROID_HOME
          
          # 接受许可证
          mkdir -p $ANDROID_HOME/licenses
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
          
          # 下载旧版 SDK 工具
          wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          unzip -q sdk-tools-linux-*.zip -d $ANDROID_HOME
          rm sdk-tools-linux-*.zip
          
          # 设置 PATH
          echo "$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          
          # 安装必要组件（避免预览版）
          yes | $ANDROID_HOME/tools/bin/sdkmanager --install \
            "platforms;android-28" \
            "build-tools;28.0.3" \
            "platform-tools" \
            "tools" \
            "emulator"

      # 3. 修复 gradlew 权限
      - name: Fix gradlew permissions
        run: |
          # 确保 gradlew 有执行权限
          chmod +x gradlew
          # 双重确认权限设置
          sudo chmod +x gradlew
          # 列出权限验证
          ls -l gradlew

      # 4. 配置 Gradle
      - name: Configure Gradle
        run: |
          # 使用兼容的 Gradle 版本
          sed -i 's/distributionUrl=.*/distributionUrl=https\\:\/\/services.gradle.org\/distributions\/gradle-4.10.3-bin.zip/' gradle/wrapper/gradle-wrapper.properties
          
          # 清理缓存
          rm -rf ~/.gradle/caches

      # 5. 构建项目
      - name: Build with Gradle
        run: |
          # 显示环境信息
          java -version
          ./gradlew --version
          
          # 执行构建
          ./gradlew build --stacktrace
