name: Android CI (Java 8 Legacy)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. 严格使用 Java 8 环境
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      # 2. 手动安装兼容 Java 8 的 Android SDK 工具链
      - name: Setup Legacy Android SDK
        run: |
          # 创建基础目录结构
          mkdir -p $ANDROID_HOME/{licenses,platforms,build-tools}

          # 写入预接受的许可证（避免交互式确认）
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license

          # 下载专为 Java 8 适配的旧版命令行工具（2021年发布）
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip -q commandlinetools-linux-*.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools-linux-*.zip

          # 安装兼容组件（注意版本号）
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-30" \
            "build-tools;30.0.3" \
            "platform-tools" \
            "tools"

          # 配置环境变量
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      # 3. 配置兼容的 Gradle 版本
      - name: Configure Gradle Wrapper
        run: |
          # 使用 Gradle 6.9.4（最后一个完美支持 Java 8 的版本）
          sed -i 's/distributionUrl=.*/distributionUrl=https\\:\/\/services.gradle.org\/distributions\/gradle-6.9.4-bin.zip/' gradle/wrapper/gradle-wrapper.properties

      # 4. 构建验证
      - name: Verify Environment
        run: |
          java -version
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list
          ./gradlew --version

      # 5. 执行构建
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
